# Generated by Django 5.2 on 2025-04-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
