# Generated by Django 5.2 on 2025-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_devicecontrol_last_triggered'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecontrol',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
